// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhxlJ_0ncIMfWenEeSSv70fFF72GoW7s',
    appId: '1:758428088032:web:c43266f04bfeb71a074285',
    messagingSenderId: '758428088032',
    projectId: 'skillcompass-project',
    authDomain: 'skillcompass-project.firebaseapp.com',
    storageBucket: 'skillcompass-project.firebasestorage.app',
    measurementId: 'G-9X0W0DFV5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLzug-KfE1try2hqAV8F6yOdpdS1szHA',
    appId: '1:758428088032:android:e45ccac37ccb9804074285',
    messagingSenderId: '758428088032',
    projectId: 'skillcompass-project',
    storageBucket: 'skillcompass-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVAzd5ulDhdrglib4sMxh0NS-czJ-h-70',
    appId: '1:758428088032:ios:0087ceffe1dc5458074285',
    messagingSenderId: '758428088032',
    projectId: 'skillcompass-project',
    storageBucket: 'skillcompass-project.firebasestorage.app',
    iosBundleId: 'com.example.skillcompassFrontend',
  );
}
