name: skillcompass_frontend
description: "A new Flutter project."
publish_to: 'none' # Private package, pub.dev'e yayınlanmaz

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0' # SDK sürüm aralığını biraz genişlettik, 3.7.2 zaten uyumlu

dependencies:
  flutter:
    sdk: flutter

  # UI ve ikonlar
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  lottie: ^3.1.2
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # State yönetimi
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1

  # Serileştirme ve modelleme
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  # Yardımcı paketler
  share_plus: ^10.0.3
  uuid: ^4.5.1
  intl: ^0.19.0
  http: ^1.2.2
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18 # Analiz raporu için markdown desteği

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.4.4 # freezed_annotation ile uyumlu sürüm

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/analysis.json
    - assets/lottie/loading.json
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg